version: '3.8'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
    networks:
      - expencetracker-network
  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - expencetracker-network
networks:
  expencetracker-network:
    driver: bridge