# Generated by Django 4.2.16 on 2025-06-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionhistory",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
