# Generated by Django 4.2.16 on 2025-06-10 04:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_alter_transactionhistory_created_at"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TransactionHistory",
            new_name="TrackingHistory",
        ),
    ]
