# Generated by Django 4.2.16 on 2025-06-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0003_rename_transactionhistory_trackinghistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_info", models.TextField()),
                ("request_type", models.CharField(max_length=100)),
                ("request_method", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name="trackinghistory",
            old_name="expence_type",
            new_name="expense_type",
        ),
        migrations.AlterField(
            model_name="trackinghistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="trackinghistory",
            name="description",
            field=models.CharField(max_length=200),
        ),
    ]
